### ISSUE TITLE
模型报错了。。RuntimeError: mat1 and mat2 shapes cannot be multiplied (1368x768 and 1024x256)

### ISSUE THREAD

**Issue by lzf00** [xhw205/GPLinker_torch#7]
Traceback (most recent call last):
  File "/content/drive/MyDrive/GPLinker_torch-main/main.py", line 85, in <module>
    logits1, logits2, logits3 = net(batch_token_ids, batch_mask_ids, batch_token_type_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/GPLinker_torch-main/main.py", line 53, in forward
    mention_outputs = self.mention_detect(outputs, batch_mask_ids)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/GPLinker_torch-main/nets/gpNet.py", line 67, in forward
    outputs = self.dense(last_hidden_state)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1368x768 and 1024x256)

**Comment by lzf00** [comment]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1224x768 and 1024x256)，而且每次运行，这个mat1的矩阵维度会变。。。。。不知道在哪里修改，是设置了随机值吗

**Comment by xhw205** [comment]
怎么会出现768，你用的是bert-base吗？
维度每次都变，肯定是random sample的原因，每次mini-batch的长度不会一致

**Comment by szt852** [comment]
我也是这个问题，请问作者和楼主解决了吗

**Comment by szt852** [comment]
我也是这个问题，请问作者和楼主解决了吗

**Comment by szt852** [comment]
我也是这个问题，请问作者和楼主解决了吗

**Comment by ExcaliburPro** [comment]
> 我也是这个问题，请问作者和楼主解决了吗

您好，我也出现了这个，试了autotokenizer也没用，请问您解决了吗

**Comment by szt852** [comment]
没有解决，不过你是从哪里知道我邮箱的啊，我这个问题问了很久了，在哪儿问的我都忘记了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xhw205/GPLinker_torch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月25日(星期六) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xhw205/GPLinker_torch] 模型报错了。。RuntimeError: mat1 and mat2 shapes cannot be multiplied (1368x768 and 1024x256) (Issue #7)





  
我也是这个问题，请问作者和楼主解决了吗
  
您好，我也出现了这个，试了autotokenizer也没用，请问您解决了吗

**Comment by xhw205** [comment]
main.py中
RawGlobalPointer(hiddensize=1024)这些地方对应改成base的hidden size了吗？
